### ISSUE TITLE
【queue】Kafka

### ISSUE THREAD

**Issue by MrYueQ** [MrYueQ/trace#22]
查看话题的描述信息时，发现 leader 为 -1 
```yaml
Topic:ops-crm-prod      PartitionCount:40       ReplicationFactor:3     Configs:
        Topic: ops-crm-prod     Partition: 0    Leader: 4       Replicas: 1,4,5 Isr: 4,1
        Topic: ops-crm-prod     Partition: 1    Leader: -1      Replicas: 4,5,0 Isr: 5
```

已在配置文件中开启
```yaml
unclean.leader.election.enable=true
```
