### ISSUE TITLE
【docker】register

### ISSUE THREAD

**Issue by MrYueQ** [MrYueQ/trace#24]
```yaml
{
  "registry-mirrors": [
    "https://registry.docker-cn.com"
  ], 
  "dns" : [
    "114.114.114.114","8.8.8.8"
  ],
  "log-driver":"json-file",
  "log-opts": {
    "max-size":"500m",
    "max-file":"3",
    "labels": "{{.ID}}/{{.ImageName}}/{{.Name}}"
}
}
```

**Comment by MrYueQ** [comment]
> docker swarm create service
```yaml
docker service create --name sg_prod_nginx_es  --constraint  node.labels.project==sgdata --constraint node.labels.service==logstash --secret ca.crt --secret source=conf.sg.prod.NginxToEs,target=/usr/share/logstash/pipeline/logstash.conf --publish published=19103,target=9600  dockerRegistor/ops/logstash:v1.1
```

**Comment by MrYueQ** [comment]
> 删除私有仓库的镜像
```yaml
1. http://YourPrivateRegistyIP:5000/v2/_catalog
2.http://YourPrivateRegistyIP:5000/v2/<name>/tags/list
3. curl -v --silent -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -X GET http://localhost:5000/v2/<name>/manifests/<tag> 2>&1 | grep Docker-Content-Digest | awk '{print ($3)}'
4. 
```

https://stackoverflow.com/questions/25436742/how-to-delete-images-from-a-private-docker-registry

**Comment by MrYueQ** [comment]
> docker service not start

- version
```yaml
docker version 
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:03:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

- status
```yaml
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: https://docs.docker.com
```

- start 

```yaml
systemctl start docker 
Failed to start docker.service: Unit not found.
```
