### ISSUE TITLE
【prometheus】snmp

### ISSUE THREAD

**Issue by MrYueQ** [MrYueQ/trace#25]
> snmp config
```yaml
public:
  auth:
    community: public
```
> prometheus config
```yaml
  - job_name: snmp
    metrics_path: /snmp
    consul_sd_configs:
      - server: 'consul_client_http_port'
        scheme: 'http'
        tags: [ "snmp"]

    relabel_configs:
      - target_label: __address__
        replacement: 'snmp_exporter_address':9116

      - source_labels: ['__meta_consul_service_metadata_zone']
        regex:         '(.*)'
        target_label:  'zone'
        replacement:   '$1'
      - source_labels: ['__meta_consul_service_metadata_hostname']
        regex:         '(.*)'
        target_label:  'hostname'
        replacement:   '$1'
      - source_labels: ['__meta_consul_service_metadata_project']
        regex:         '(.*)'
        target_label:  'project'
        replacement:   '$1'
      - source_labels: ['__meta_consul_service_address']
        regex:         '(.*)'
        target_label:  '__param_target'
        replacement:   '$1'
      - source_labels: ['__meta_consul_service_metadata_module']
        regex:         '(.*)'
        target_label:  '__param_module'
        replacement:   '$1'
```

> grafana 
![image](https://user-images.githubusercontent.com/14846522/96682514-82385f80-13ab-11eb-9a73-11d4d7345712.png)
