### ISSUE TITLE
[logstash] multiple pipeline

### ISSUE THREAD

**Issue by MrYueQ** [MrYueQ/trace#6]
- delete logstash sample

    ```bash
     rm -f logstash-sample.conf 
     ```
- pipelines

   ```yaml
   - pipeline.id: post
      path.config: "/etc/logstash/conf.d/post.collect.conf"

   - pipeline.id: get
      path.config: "/etc/logstash/conf.d/get.collect.conf"
   ```
