### ISSUE TITLE
[prometheus] federate

### ISSUE THREAD

**Issue by MrYueQ** [MrYueQ/trace#8]
#### 联邦模式下

```yaml
  - job_name: 'federate'
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{project=~"test11|test33|ops|bigdata|test222"}'
        - '{project="test1"}'
        - '{project="test"}'

    static_configs:
      - targets:
        - 'node01:9090'
        - 'node02:9090'
```
